### ISSUE TITLE
building issues

### ISSUE THREAD

**Issue by timotheecour** [drepl/drepl#1]
$dub
Failed to retrieve metadata for package vibe-d: Could not find package candidate for vibe-d >=0.7.18
Failed to retrieve metadata for package dscanner: Could not find package candidate for dscanner ~master
Failed to retrieve metadata for package linenoise: Could not find package candidate for linenoise ~master
Could not resolve dependencies
The dependency graph could not be filled, there are unresolved dependencies.
The following changes will be performed:
Failure vibe-d >=0.7.18, userWide
Issued by:
 drepl: >=0.7.18
Failure dscanner ~master, userWide
Issued by:
 drepl: ~master
Failure linenoise ~master, userWide
Issued by:
 drepl: ~master
Error executing command run: Unknown dependency: vibe-d

**Comment by MartinNowak** [comment]
Think that is resolved by now.
