### ISSUE TITLE
Have an official dlang REPL

### ISSUE THREAD

**Issue by wilzbach** [drepl/drepl#37]
Currently there is drepl and [dabble](https://github.com/callumenator/dabble), both weren't compilable when I looked at them. It seems to me that having a working REPL is nowadays an essential feature of a language and we should try to get some manpower and maintainer on this. Even [C++](https://root.cern.ch/cling) has this!

How about this agenda?

1) Bring <repo> in a good shape (not perfect)
2) Move to github.com/dlang/repl
3) Get it stable
4) Include into release with dmd, rdmd and dub (as idmd)
5) Continue with more features

**Comment by carljv** [comment]
:+1: for this. If this repo is unmaintained now and should be forked, I'm on board.

**Comment by wilzbach** [comment]
> :+1: for this. If this repo is unmaintained now and should be forked, I'm on board.

I have pushed my working fork to [drepl/drepl](https://github.com/drepl/drepl). That's probably the easiest and at some point we hopefully can move over to the dlang namespace.
So let's make further plans over there?

**Comment by MartinNowak** [comment]
Let me at least transfer the repo so we maintain the issue tracker.

**Comment by wilzbach** [comment]
> Let me at least transfer the repo so we maintain the issue tracker.

Great to hear that you are alive - you should have full admin acces. Feel free to move ;-)

**Comment by MartinNowak** [comment]
We first need to delete the other repo, I'll try to migrate the issues over to here.

**Comment by wilzbach** [comment]
> We first need to delete the other repo, I'll try to migrate the issues over to here.

No worries - I renamed it to `drepl-old`, so we can do this after you moved it over.
It's just two issues, so just removing them shouldn't hurt.

**Comment by MartinNowak** [comment]
Already done

**Comment by wilzbach** [comment]
> Already done

Great - then I close this issue and once we feel confident enough, we can propose that's moved to `dlang`?

**Comment by wilzbach** [comment]
> Already done

I forgot: Thanks a lot, Martin!
