### ISSUE TITLE
Register on code.dlang.org

### ISSUE THREAD

**Issue by wilzbach** [drepl/drepl#51]
@MartinNowak do you want to register drepl on dub, s.t. ideally it's just:

```
dub run drepl
```

**Comment by wilzbach** [comment]
I guess currently the biggest problem is to bootstrap / install the C library? Is there a nice way to handle that? (see also https://github.com/dlang/dub/issues/852)

**Comment by MartinNowak** [comment]
At best replacing it with a D library, at worst shipping object files with drepl.

**Comment by MartinNowak** [comment]
It works w/ a system wide installation of liblinenoise available on most distributions.
So we just need to document that and maybe detect missing libs in the dub file (or can dub already do that)?

**Comment by wilzbach** [comment]
https://code.dlang.org/packages/drepl
